"""empty message

Revision ID: 7ef7d3715ac3
Revises: 
Create Date: 2017-06-22 20:02:45.272168

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7ef7d3715ac3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('players', 'num_games_played')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('players', sa.Column('num_games_played', sa.INTEGER(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
