"""empty message

Revision ID: 9a37e6f837a0
Revises: 52dbef344eb0
Create Date: 2017-06-22 20:32:04.468619

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '9a37e6f837a0'
down_revision = '52dbef344eb0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('players')
    op.drop_table('games')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('games',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('player1_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('player2_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('winner_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('started_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('finished_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['player1_id'], ['players.id'], name='games_player1_id_fkey'),
    sa.ForeignKeyConstraint(['player2_id'], ['players.id'], name='games_player2_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='games_pkey')
    )
    op.create_table('players',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('username', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('ranking', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='players_pkey')
    )
    # ### end Alembic commands ###
